// Auto-generated by ts-rs (Stage S4 Protocol Contract)
// DO NOT EDIT MANUALLY - run `make codegen` to update.

export type ProofIntent = "Submit" | "Check";

export type SearchRange = { min_elo: number, max_elo: number, };

export type PlayerInfo = { player_id: string, username: string | null, elo: number, };

export type Problem = { id: string, goal: string, imports: Array<string>, difficulty: number, category: string, hint: string | null, duration_ms: bigint, };

export type VerdictStatus = "Accepted" | "Rejected" | "Error";

export type RejectReason = { "type": "LeaningFailed" } | { "type": "TimedOut" } | { "type": "UsesSorry" } | { "type": "TooLarge" } | { "type": "RejectedByFilter", "detail": string } | { "type": "Busy" } | { "type": "Internal", "detail": string };

export type DiagnosticSeverity = "error" | "warning" | "info";

export type Diagnostic = { line: number, col: number, end_line: number, end_col: number, severity: DiagnosticSeverity, message: string, };

export type OpponentStatus = "Idle" | "Typing" | "Checking" | "Verifying" | "Submitted";

export type MatchOutcome = "Won" | "Lost" | "Draw" | "ForfeitWin" | "ForfeitLoss";

export type ClientMessage = { "type": "Hello", version: number, token: string | null, username: string | null, } | { "type": "QueueJoin", } | { "type": "QueueLeave", } | { "type": "PracticeJoin", } | { "type": "ProofRequest", req_id: string, code: string, intent: ProofIntent, } | { "type": "Resign", } | { "type": "Pong", ts: bigint, };

export type ServerMessage = { "type": "Welcome", player_id: string, session_token: string, server_time_ms: bigint, heartbeat_interval_ms: bigint, protocol_version: number, } | { "type": "ServerTime", server_time_ms: bigint, } | { "type": "QueueStatus", queue_size: number, elo: number, search_range: SearchRange, } | { "type": "MatchFound", room_id: string, you: PlayerInfo, opponent: PlayerInfo, } | { "type": "RoundStart", room_id: string, problem: Problem, starts_at_ms: bigint, ends_at_ms: bigint, duration_ms: bigint, server_time_ms: bigint, seq: bigint, } | { "type": "Verdict", req_id: string, verdict: VerdictStatus, reason: RejectReason | null, message: string, diagnostics: Array<Diagnostic>, elapsed_ms: bigint, check_skipped: boolean, } | { "type": "OpponentActivity", status: OpponentStatus, } | { "type": "RoundEnd", room_id: string, outcome: MatchOutcome, winner_id: string | null, winning_proof: string | null, canonical_proof: string | null, elo_delta: number, duration_ms: bigint, seq: bigint, } | { "type": "ServerError", code: string, message: string, retry_after_ms: bigint | null, retryable: boolean, } | { "type": "Pong", ts: bigint, };

